<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
        <PackageReference Include="System.Memory" />
    </ItemGroup>

    <!-- NuGet -->
    <Import Project="../NuGet.props" />
    <PropertyGroup>
        <PackageId>XSitemaps</PackageId>
        <Description>Simple sitemap.xml serializer for better SEO.</Description>
    </PropertyGroup>

</Project>
