<Project>
    
    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <Version>1.2.0.0</Version>
        <PackageProjectUrl>https://github.com/xin9le/XSitemaps</PackageProjectUrl>
        <PackageTags>Sitemap, XML, SEO</PackageTags>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>$(PackageProjectUrl)</RepositoryUrl>
        <RepositoryType>Git</RepositoryType>
        <Company />
        <Authors>xin9le</Authors>
        <Copyright>Copyright© xin9le, All rights reserved.</Copyright>
        <PackageReleaseNotes></PackageReleaseNotes>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../../README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>