<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="MSTest" Version="4.0.2" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
  </ItemGroup>    
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageVersion Include="System.Memory" Version="4.6.3" />
  </ItemGroup>
</Project>